docker pull openwhisk/apigateway
docker pull apache/couchdb
docker pull openwhisk/controller
docker pull wurstmeister/kafka
docker pull openwhisk/ow-utils
docker pull zookeeper
docker pull nginx
docker pull redis
docker pull busybox
docker pull openwhisk/alarmprovider
docker pull openwhisk/kafkaprovider